SELECT USER
FROM DUAL;
-- HR

-- 세 개 이상의 테이블 조인(JOIN, 결합)

-- 형식 1. (SQL 1992 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블명2.컬럼명1
        AND 테이블명2.컬럼명2 = 테이블명3.컬럼명2;

-- 형식 2. (SQL 1999 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
    JOIN 테이블3
    ON 테이블명2.컬럼명2 = 테이블명3.컬럼명2;
    
-- HR 계정 소유의 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
/*
COUNTRIES	TABLE	
DEPARTMENTS	TABLE	
EMPLOYEES	TABLE	
EMP_DETAILS_VIEW	VIEW	
JOBS	TABLE	
JOB_HISTORY	TABLE	
LOCATIONS	TABLE	
REGIONS	TABLE	
*/

-- ㅇ HR.JOBS, HR.EMPLOYEES, HR.DEPARTMENTS 테이블을 대상으로 
-- 직원들의 데이터를 EMPLOYEES.FRIST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME 항목을 조회
SELECT *
FROM JOBS; -- 관계 컬럼 

SELECT *
FROM EMPLOYEES;  -- 관계컬럼

SELECT *
FROM DEPARTMENTS; -- 관계 컬럼 

SELECT B.FIRST_NAME, B.LAST_NAME, A.JOB_TITLE, C.DEPARTMENT_NAME
FROM JOBS A JOIN EMPLOYEES B
    ON A.JOB_ID = B.JOB_ID
    LEFT JOIN DEPARTMENTS C
    ON B.DEPARTMENT_ID = C.DEPARTMENT_ID;

SELECT B.FIRST_NAME, B.LAST_NAME, A.JOB_TITLE, C.DEPARTMENT_NAME
FROM JOBS A, EMPLOYEES B, DEPARTMENTS C
WHERE A.JOB_ID = B.JOB_ID AND B.DEPARTMENT_ID = C.DEPARTMENT_ID(+);

-----------------------------------------------------------------------------

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT COUNT(*)
FROM EMPLOYEES;
-- 107

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, J.JOB_TITLE
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID;

-- EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS, COUNTRIES, REGIOUS 테이블을 대상으로
-- 직원들의 데이터를 다음과 같이 조회 
-- FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME, LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME

SELECT *
FROM JOBS; -- 관계 컬럼 

SELECT *
FROM EMPLOYEES;  -- 관계컬럼

SELECT *
FROM DEPARTMENTS; -- 관계 컬럼 

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS;

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, J.JOB_TITLE,L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    LEFT JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
    LEFT JOIN LOCATIONS L 
    ON D.LOCATION_ID = L.LOCATION_ID
    LEFT JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID
    LEFT  JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID;
    
    
SELECT B.FIRST_NAME, B.LAST_NAME, A.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM JOBS A, EMPLOYEES B, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE A.JOB_ID = B.JOB_ID 
    AND B.DEPARTMENT_ID(+) = D.DEPARTMENT_ID 
    AND D.LOCATION_ID(+) = L.LOCATION_ID 
    AND C.COUNTRY_ID = L.COUNTRY_ID 
    AND R.REGION_ID = C.REGION_ID(+);