-- 일,월,별 프로젝트 개수 
SELECT ONE, TWO, THREE, FOUR
FROM DAY_PRO_VIEW;
 
SELECT ONE, TWO, THREE, FOUR
FROM WEEK_PRO_VIEW;
   
SELECT ONE, TWO, THREE, FOUR
FROM MONTH_PRO_VIEW;

---------------- 일, 월, 별 프로젝트 개수 가져오기 

-- 이거 신고 받은 개수를 가져오가 그냥
SELECT *
FROM AO_REPORT;

SELECT *
FROM AOC_REPORT;

SELECT *
FROM AO2_REPORT;

-- 일 별로 모든 신고의 개수 
CREATE OR REPLACE VIEW TODAY_REPORT_VIEW
AS
SELECT AO + AOC + AO2 + TQ + TQC + TQ2 + CQ + CQC + CQ2 + P + PC + P2 + TEAM AS ONE
    , AO_1 + AOC_1 + AO2_1 + TQ_1 + TQC_1 + TQ2_1 + CQ_1+ CQC_1 + CQ2_1 + P_1 + PC_1 + P2_1 + TEAM_1 AS TWO
    , AO_2 + AOC_2 + AO2_2 + TQ_2 + TQC_2 + TQ2_2 + CQ_2 + CQC_2 + CQ2_2 + P_2 + PC_2 + P2_2 + TEAM_2 AS THREE
    , AO_3 + AOC_3 + AO2_3 + TQ_3 + TQC_3 + TQ2_3 + CQ_3 + CQC_3 + CQ2_3 + P_3 + PC_3 + P2_3 + TEAM_3 AS FOUR 
FROM ( 
        SELECT COUNT(*) AS AO
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS AO2
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS TQ
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS TQC
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TQ2
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )     ,
     (
        SELECT COUNT(*) AS CQ
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS CQC
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS CQ2
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS PC
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P2
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TEAM
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,( 
        SELECT COUNT(*) AS AO_1
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_1
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

     )
     ,
     (
        SELECT COUNT(*) AS AO2_1
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

     )
     ,
     (
        SELECT COUNT(*) AS TQ_1
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1
    )
    ,
    (
        SELECT COUNT(*) AS TQC_1
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_1
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
     (
        SELECT COUNT(*) AS CQ_1
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1
    )
    ,
    (
        SELECT COUNT(*) AS CQC_1
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_1
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS P_1
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS PC_1
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS P2_1
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_1
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-1
    )
    
    ,( 
        SELECT COUNT(*) AS AO_2
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_2
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

     )
     ,
     (
        SELECT COUNT(*) AS AO2_2
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

     )
     ,
     (
        SELECT COUNT(*) AS TQ_2
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2
    )
    ,
    (
        SELECT COUNT(*) AS TQC_2
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_2
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
     (
        SELECT COUNT(*) AS CQ_2
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2
    )
    ,
    (
        SELECT COUNT(*) AS CQC_2
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_2
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS P_2
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS PC_2
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS P2_2
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_2
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-2
    )
    
    ,( 
        SELECT COUNT(*) AS AO_3
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_3
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

     )
     ,
     (
        SELECT COUNT(*) AS AO2_3
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

     )
     ,
     (
        SELECT COUNT(*) AS TQ_3
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3
    )
    ,
    (
        SELECT COUNT(*) AS TQC_3
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_3
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
         ,
     (
        SELECT COUNT(*) AS CQ_3
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3
    )
    ,
    (
        SELECT COUNT(*) AS CQC_3
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_3
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS P_3
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS PC_3
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS P2_3
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_3
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')-3
    );
--==>> View TODAY_REPORT_VIEW이(가) 생성되었습니다.

SELECT *
FROM TODAY_REPORT_VIEW;

----------- 주 단위 신고 개수 
CREATE OR REPLACE VIEW WEEK_REPORT_VIEW
AS
SELECT AO + AOC + AO2 + TQ + TQC + TQ2 + CQ + CQC + CQ2 + P + PC + P2 + TEAM AS ONE
    , AO_1 + AOC_1 + AO2_1 + TQ_1 + TQC_1 + TQ2_1 + CQ_1+ CQC_1 + CQ2_1 + P_1 + PC_1 + P2_1 + TEAM_1 AS TWO
    , AO_2 + AOC_2 + AO2_2 + TQ_2 + TQC_2 + TQ2_2 + CQ_2 + CQC_2 + CQ2_2 + P_2 + PC_2 + P2_2 + TEAM_2 AS THREE
    , AO_3 + AOC_3 + AO2_3 + TQ_3 + TQC_3 + TQ2_3 + CQ_3 + CQC_3 + CQ2_3 + P_3 + PC_3 + P2_3 + TEAM_3 AS FOUR
FROM ( 
        SELECT COUNT(*) AS AO
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
     )
     ,
     (
        SELECT COUNT(*) AS AO2
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS TQ
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS TQC
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TQ2
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )     ,
     (
        SELECT COUNT(*) AS CQ
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS CQC
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS CQ2
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS PC
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P2
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TEAM
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,( 
        SELECT COUNT(*) AS AO_1
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')
     )
     ,
     (
        SELECT COUNT(*) AS AOC_1
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS AO2_1
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS TQ_1
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS TQC_1
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_1
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
     (
        SELECT COUNT(*) AS CQ_1
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS CQC_1
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_1
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P_1
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS PC_1
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P2_1
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_1
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    
    ,( 
        SELECT COUNT(*) AS AO_2
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_2
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS AO2_2
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS TQ_2
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS TQC_2
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_2
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
     (
        SELECT COUNT(*) AS CQ_2
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS CQC_2
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_2
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P_2
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS PC_2
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P2_2
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_2
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    
    ,( 
        SELECT COUNT(*) AS AO_3
        FROM AO_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_3
        FROM AOC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS AO2_3
        FROM AO2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

     )
     ,
     (
        SELECT COUNT(*) AS TQ_3
        FROM TQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS TQC_3
        FROM TQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_3
        FROM TQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
         ,
     (
        SELECT COUNT(*) AS CQ_3
        FROM CQ_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
    (
        SELECT COUNT(*) AS CQC_3
        FROM CQC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_3
        FROM CQ2_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P_3
        FROM P_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS PC_3
        FROM PC_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS P2_3
        FROM P2_REPORT 
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_3
        FROM TEAM_REPORT
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')
    );
--==>> View WEEK_REPORT_VIEW이(가) 생성되었습니다.

----------- 월 단위 신고 개수 
CREATE OR REPLACE VIEW MONTH_REPORT_VIEW
AS
SELECT AO + AOC + AO2 + TQ + TQC + TQ2 + CQ + CQC + CQ2 + P + PC + P2 + TEAM AS ONE
    , AO_1 + AOC_1 + AO2_1 + TQ_1 + TQC_1 + TQ2_1 + CQ_1+ CQC_1 + CQ2_1 + P_1 + PC_1 + P2_1 + TEAM_1 AS TWO
    , AO_2 + AOC_2 + AO2_2 + TQ_2 + TQC_2 + TQ2_2 + CQ_2 + CQC_2 + CQ2_2 + P_2 + PC_2 + P2_2 + TEAM_2 AS THREE
    , AO_3 + AOC_3 + AO2_3 + TQ_3 + TQC_3 + TQ2_3 + CQ_3 + CQC_3 + CQ2_3 + P_3 + PC_3 + P2_3 + TEAM_3 AS FOUR
FROM ( 
        SELECT COUNT(*) AS AO
        FROM AO_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC
        FROM AOC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
     )
     ,
     (
        SELECT COUNT(*) AS AO2
        FROM AO2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

     )
     ,
     (
        SELECT COUNT(*) AS TQ
        FROM TQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
    )
    ,
    (
        SELECT COUNT(*) AS TQC
        FROM TQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS TQ2
        FROM TQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )     ,
     (
        SELECT COUNT(*) AS CQ
        FROM CQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
    )
    ,
    (
        SELECT COUNT(*) AS CQC
        FROM CQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS CQ2
        FROM CQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS P
        FROM P_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS PC
        FROM PC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS P2
        FROM P2_REPORT 
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,
    (
        SELECT COUNT(*) AS TEAM
        FROM TEAM_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)

    )
    ,( 
        SELECT COUNT(*) AS AO_1
        FROM AO_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))
     )
     ,
     (
        SELECT COUNT(*) AS AOC_1
        FROM AOC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

     )
     ,
     (
        SELECT COUNT(*) AS AO2_1
        FROM AO2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

     )
     ,
     (
        SELECT COUNT(*) AS TQ_1
        FROM TQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))
    )
    ,
    (
        SELECT COUNT(*) AS TQC_1
        FROM TQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_1
        FROM TQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
     (
        SELECT COUNT(*) AS CQ_1
        FROM CQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))
    )
    ,
    (
        SELECT COUNT(*) AS CQC_1
        FROM CQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_1
        FROM CQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS P_1
        FROM P_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS PC_1
        FROM PC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS P2_1
        FROM P2_REPORT 
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_1
        FROM TEAM_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))
    )
    
    ,( 
        SELECT COUNT(*) AS AO_2
        FROM AO_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_2
        FROM AOC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

     )
     ,
     (
        SELECT COUNT(*) AS AO2_2
        FROM AO2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

     )
     ,
     (
        SELECT COUNT(*) AS TQ_2
        FROM TQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))
    )
    ,
    (
        SELECT COUNT(*) AS TQC_2
        FROM TQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_2
        FROM TQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
     (
        SELECT COUNT(*) AS CQ_2
        FROM CQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))
    )
    ,
    (
        SELECT COUNT(*) AS CQC_2
        FROM CQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_2
        FROM CQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS P_2
        FROM P_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS PC_2
        FROM PC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS P2_2
        FROM P2_REPORT 
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_2
        FROM TEAM_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))
    )
    
    ,( 
        SELECT COUNT(*) AS AO_3
        FROM AO_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))
        
     )
     ,
     (
        SELECT COUNT(*) AS AOC_3
        FROM AOC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

     )
     ,
     (
        SELECT COUNT(*) AS AO2_3
        FROM AO2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

     )
     ,
     (
        SELECT COUNT(*) AS TQ_3
        FROM TQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))
    )
    ,
    (
        SELECT COUNT(*) AS TQC_3
        FROM TQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS TQ2_3
        FROM TQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
         ,
     (
        SELECT COUNT(*) AS CQ_3
        FROM CQ_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))
    )
    ,
    (
        SELECT COUNT(*) AS CQC_3
        FROM CQC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS CQ2_3
        FROM CQ2_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS P_3
        FROM P_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS PC_3
        FROM PC_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS P2_3
        FROM P2_REPORT 
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    )
    ,
    (
        SELECT COUNT(*) AS TEAM_3
        FROM TEAM_REPORT
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))
    );

-- 일,월,별 프로젝트 개수 
SELECT ONE,TWO,THREE,FOUR
FROM DAY_PRO_VIEW;
 
SELECT ONE,TWO,THREE,FOUR
FROM WEEK_PRO_VIEW;
   
SELECT ONE,TWO,THREE,FOUR
FROM MONTH_PRO_VIEW;

-- 신고 일,주,월 별 개수 뽑아옴 
SELECT ONE,TWO,THREE,FOUR
FROM TODAY_REPORT_VIEW;

SELECT ONE,TWO,THREE,FOUR
FROM WEEK_REPORT_VIEW;

SELECT ONE,TWO,THREE,FOUR
FROM MONTH_REPORT_VIEW;

-- 회원 수 일별로 뽑아오기
CREATE OR REPLACE VIEW TODAY_MEMBER_VIEW
AS
SELECT ONE,TWO,THREE,FOUR
FROM 
    (
        SELECT COUNT(*) AS ONE
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
    )
    ,
     (
        SELECT COUNT(*) AS TWO
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-1,'YYYY-MM-DD'),'YYYY-MM-DD')

    )
    ,
     (
        SELECT COUNT(*) AS THREE
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-2,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
     (
        SELECT COUNT(*) AS FOUR
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-3,'YYYY-MM-DD'),'YYYY-MM-DD')
    );
--==>> View TODAY_MEMBER_VIEW이(가) 생성되었습니다.

-- 회원 수 주별로 뽑아오기
CREATE OR REPLACE VIEW WEEK_MEMBER_VIEW
AS
SELECT ONE,TWO,THREE,FOUR
FROM 
    (
        SELECT COUNT(*) AS ONE
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
    )
    ,
     (
        SELECT COUNT(*) AS TWO
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-7,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
     (
        SELECT COUNT(*) AS THREE
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-14,'YYYY-MM-DD'),'YYYY-MM-DD')
    )
    ,
     (
        SELECT COUNT(*) AS FOUR
        FROM MEMBER
        WHERE TO_DATE(TO_CHAR(KDATE,'YYYY-MM-DD'),'YYYY-MM-DD') <= TO_DATE(TO_CHAR(SYSDATE-21,'YYYY-MM-DD'),'YYYY-MM-DD')
    );
    
-- 회원 수 월별로 뽑아오기
CREATE OR REPLACE VIEW MONTH_MEMBER_VIEW
AS
SELECT ONE,TWO,THREE,FOUR
FROM 
    (
        SELECT COUNT(*) AS ONE
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(SYSDATE)
    )
    ,
     (
        SELECT COUNT(*) AS TWO
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -1))
    )
    ,
     (
        SELECT COUNT(*) AS THREE
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -2))
    )
    ,
     (
        SELECT COUNT(*) AS FOUR
        FROM MEMBER
        WHERE TRUNC(TO_DATE(KDATE, 'YYYY-MM-DD')) <= TRUNC(ADD_MONTHS(TO_DATE(SYSDATE,'YYYY-MM-DD'), -3))

    );
    
----------------------------------------------------
SELECT *
FROM TODAY_MEMBER_VIEW;
    
SELECT *
FROM WEEK_MEMBER_VIEW;    
    
SELECT *
FROM MONTH_MEMBER_VIEW;