-- 일,월,별 프로젝트 개수 
SELECT ONE,TWO,THREE,FOUR
FROM DAY_PRO_VIEW;
 
SELECT ONE,TWO,THREE,FOUR
FROM WEEK_PRO_VIEW;
   
SELECT ONE,TWO,THREE,FOUR
FROM MONTH_PRO_VIEW;


-- 신고 일,주,월 별 개수 뽑아옴 
SELECT ONE,TWO,THREE,FOUR
FROM TODAY_REPORT_VIEW;

SELECT ONE,TWO,THREE,FOUR
FROM WEEK_REPORT_VIEW;

SELECT ONE,TWO,THREE,FOUR
FROM MONTH_REPORT_VIEW;
----------------------------------- 전체 회원 조회 
SELECT ONE,TWO,THREE,FOUR
FROM TODAY_MEMBER_VIEW;
    
SELECT ONE,TWO,THREE,FOUR
FROM WEEK_MEMBER_VIEW;    
    
SELECT ONE,TWO,THREE,FOUR
FROM MONTH_MEMBER_VIEW;

-------------------------------------------------------------------------------------------------------------------------------------
--들어온 신고 조회
SELECT *
FROM AO_REPORT;

-- 개설 게시판 신고
CREATE OR REPLACE VIEW PRO_GET_REPORT_VIEW
AS
SELECT M.MEM_CODE, M.ID,M.NICKNAME,AO.AOR_CODE AS CODE, RR.REASON,AO.CONTENT, AO.KDATE, NVL(AOR.AOP_CODE,-1) AS PENALTY
FROM AO_REPORT AO 
    LEFT JOIN  AO_PROCESS AOR ON AOR.AOR_CODE = AO.AOR_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE= AO.RR_CODE
    JOIN MEMBER M ON M.MEM_CODE = AO.MEM_CODE
UNION ALL
(
-- 개설 신청 댓글 신고 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, AOC.ACR_CODE, RR.REASON, AOC.CONTENT, AOC.KDATE, NVL(AOR.ACP_CODE,-1) AS PENALTY
FROM AOC_REPORT AOC
     LEFT JOIN AOC_PROCESS AOR ON aor.acr_code = aoc.acr_code
     JOIN MEMBER M ON M.MEM_CODE = AOC.MEM_CODE
     JOIN REPORT_REASON RR ON RR.RR_CODE = AOC.RR_CODE
)
UNION ALL
(
-- 개설 신청 대댓글 신고 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, AO2.A2R_CODE, RR.REASON, AO2.CONTENT, AO2.KDATE, NVL(AO2P.A2P_CODE,-1) AS PENALTY
FROM AO2_REPORT AO2
    LEFT JOIN AO2_PROCESS AO2P ON AO2P.A2R_CODE = AO2.A2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = AO2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = AO2.RR_CODE
);

SELECT MEM_CODE,ID,NICKNAME,CODE, REASON, CONTENT, TO_CHAR(KDATE,'YYYY-MM-DD') AS KDATE, PENALTY
FROM PRO_GET_REPORT_VIEW
ORDER BY MEM_CODE;

----------------------------------------------------------------------------------------------------------

-- 기술 개시판 신고 
CREATE OR REPLACE VIEW TQ_GET_REPORT_VIEW
AS
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQ.TQR_CODE AS CODE, RR.REASON, TQ.CONTENT, TQ.KDATE, NVL(TQR.TQP_CODE,-1) AS PENALTY
FROM TQ_REPORT TQ
    LEFT JOIN TQ_PROCESS TQR ON TQ.TQR_CODE = TQR.TQR_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQ.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQ.RR_CODE   
UNION ALL
(
-- 기술 게시판 댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQC.QCR_CODE, RR.REASON, TQC.CONTENT, TQC.KDATE, NVL(TQCP.QCR_CODE,-1) AS PENALTY
FROM TQC_REPORT TQC
    LEFT JOIN TQC_PROCESS TQCP ON TQCP.QCR_CODE = TQC.QCR_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQC.RR_CODE
)
UNION ALL
(
-- 기술 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQ2.Q2R_CODE, RR.REASON, TQ2.CONTENT, TQ2.KDATE, NVL(TQ2P.T2P_CODE,-1) AS PENALTY
FROM TQ2_REPORT TQ2
    LEFT JOIN TQ2_PROCESS TQ2P ON TQ2P.Q2R_CODE = TQ2.Q2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQ2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQ2.RR_CODE
);

SELECT MEM_CODE,ID,NICKNAME,CODE, REASON, CONTENT, TO_CHAR(KDATE,'YYYY-MM-DD') AS KDATE, PENALTY
FROM TQ_GET_REPORT_VIEW
WHERE PENALTY ='-1'
ORDER BY MEM_CODE;

-------------------------------------------------------------- 커리어 
CREATE OR REPLACE VIEW CQ_GET_REPORT_VIEW
AS
-- 커리어 게시판
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQ.QR_CODE AS CODE, RR.REASON, CQ.CONTENT, CQ.KDATE, NVL(CQP.QPR_CODE,-1) AS PENALTY
FROM CQ_REPORT CQ
    LEFT JOIN CQ_PROCESS CQP ON CQ.QR_CODE = CQP.QR_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQ.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQ.RR_CODE 
UNION ALL
(
--커리어 게시판 댓글 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQC.CR_CODE AS CODE, RR.REASON, CQC.CONTENT, CQC.KDATE, NVL(CQCP.QCP_CODE,-1) AS PENALTY
FROM CQC_REPORT CQC
    LEFT JOIN CQC_PROCESS CQCP ON CQC.CR_CODE = CQCP.CR_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQC.RR_CODE 
)
UNION ALL
(
-- 커리어 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQ2.C2_CODE AS CODE, RR.REASON, CQ2.CONTENT, CQ2.KDATE, NVL(CQ2P.Q2P_CODE,-1) AS PENALTY
FROM CQ2_REPORT CQ2
    LEFT JOIN CQ2_PROCESS CQ2P ON CQ2.C2_CODE = CQ2P.C2_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQ2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQ2.RR_CODE 
);

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY
FROM CQ_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

---------------------------------------------------------------------- 포트 폴리오
CREATE OR REPLACE VIEW PT_GET_REPORT_VIEW
AS
SELECT M.MEM_CODE, M.ID, M.NICKNAME, P.PR_CODE AS CODE, RR.REASON, P.CONTENT, P.KDATE, NVL(PP.PP_CODE,-1) AS PENALTY
FROM P_REPORT P
    LEFT JOIN P_PROCESS PP ON P.PR_CODE = PP.PR_CODE
    JOIN MEMBER M ON M.MEM_CODE = P.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = P.RR_CODE 
UNION ALL
(
--포트폴리오 게시판 댓글 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, PC.PCR_CODE AS CODE, RR.REASON, PC.CONTENT, PC.KDATE, NVL(PCP.PRR_CODE,-1) AS PENALTY
FROM PC_REPORT PC
    LEFT JOIN PC_PROCESS PCP ON PC.PCR_CODE = PCP.PCR_CODE
    JOIN MEMBER M ON M.MEM_CODE = PC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = PC.RR_CODE 
)
UNION ALL
(
-- 포트폴리오 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, P2.P2R_CODE AS CODE, RR.REASON, P2.CONTENT, P2.KDATE, NVL(P2P.P2P_CODE,-1) AS PENALTY
FROM P2_REPORT P2
    LEFT JOIN P2_PROCESS P2P ON P2.P2R_CODE = P2P.P2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = P2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = P2.RR_CODE 
);

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY
FROM PT_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

SELECT *
FROM PENALTY;
