SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY
FROM TQ_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

SELECT *
FROM TQ_PROCESS;

INSERT INTO TQ_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'ADMIN0001','PRE0001','PE0002','PTG0001');

-- 기술 게시판 글자 수 따온 코드 
SELECT MEM_CODE, NICKNAME, KDATE, CODE,
  CASE 
    WHEN CODE LIKE 'Q2R%' THEN 'TQ2'
    WHEN CODE LIKE 'TQR%' THEN 'TQ'
    WHEN CODE LIKE 'QCR%' THEN 'TQC'
    ELSE ''
  END AS TABLE_CODE
FROM TQ_GET_REPORT_VIEW
WHERE  +PENALTY = '-1'
ORDER BY MEM_CODE;

INSERT INTO TQ_PROCESS
VALUES (TO_CHAR('TQP' || LPAD(TQP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'ADMIN0001','PRE0001','PE0002','PTG0002','TQR0002');


INSERT INTO TQC_PROCESS
VALUES (TO_CHAR('TCP' || LPAD(TCP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'ADMIN0001','PRE0001','QCR0002','PE0002','PTG0002');


INSERT INTO TQ2_PROCESS
VALUES (TO_CHAR('T2P' || LPAD(T2P_SEQ.NEXTVAL, 4, '0')), SYSDATE,'Q2R0001','ADMIN0001','PRE0001','PE0002','PTG0002');


SELECT CODE
FROM TQ_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

SELECT *
FROM TQ_REPORT;

SELECT *
FROM TQC_REPORT;

SELECT *
FROM TQ2_REPORT;

SELECT A.ADMIN_CODE AS ADMIN, A.MEM_CODE AS MEM_CODE, M.NICKNAME AS NICKNAME
FROM ADMIN A JOIN MEMBER M ON M.MEM_CODE = A.MEM_CODE;

SELECT PTG_CODE, TARGET
FROM P_TARGET;

SELECT PE_CODE, NAME
FROM PENALTY;

SELECT PRE_CODE, REASON
FROM P_REASON;

select *
from admin;

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, TO_CHAR(KDATE,'YYYY-MM-DD') AS KDATE, PENALTY
FROM CQ_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

SELECT *
FROM CQ2_PROCESS;

INSERT INTO CQ_PROCESS
VALUES(TO_CHAR('QPR' || LPAD(QPR_SEQ.NEXTVAL, 4, '0')),SYSDATE,'ADMIN0001','PRE0002','QR0001','PE0002','PTG0003');

INSERT INTO CQC_PROCESS
VALUES(TO_CHAR('QCP' || LPAD(QCP_SEQ.NEXTVAL, 4, '0')),SYSDATE,'ADMIN0001','PRE0001','CR0001','PE0001','PTG0002');

INSERT INTO CQ2_PROCESS
VALUES(TO_CHAR('Q2P' || LPAD(Q2P_SEQ.NEXTVAL, 4, '0')),SYSDATE,'ADMIN0001','PRE0001','C20001','PE0001','PTG0002');

ROLLBACK;

SELECT *
FROM CQ_REPORT;

SELECT *
FROM CQC_REPORT;

SELECT *
FROM CQ2_REPORT;

SELECT MEM_CODE, NICKNAME, KDATE, CODE,
  CASE 
    WHEN CODE LIKE 'QR%' THEN 'CQ'
    WHEN CODE LIKE 'CR%' THEN 'CQC'
    WHEN CODE LIKE 'C2%' THEN 'CQ2'
    ELSE ''
  END AS TABLE_CODE
FROM CQ_GET_REPORT_VIEW
WHERE  +PENALTY = '-1'
ORDER BY MEM_CODE;

SELECT COUNT
FROM POST_REPORT_VIEW_TODAY;

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY
FROM PT_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;

------------------------------------------------------------------------------ 포트폴리오 
-- 테이블 가려내기
SELECT MEM_CODE, NICKNAME, KDATE, CODE,
  CASE 
    WHEN CODE LIKE 'PR%' THEN 'P'
    WHEN CODE LIKE 'PCR%' THEN 'PC'
    WHEN CODE LIKE 'P2R%' THEN 'P2'
    ELSE ''
  END AS TABLE_CODE
FROM PT_GET_REPORT_VIEW
WHERE  PENALTY = '-1'
ORDER BY MEM_CODE;

INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0011','ADMIN0001','PRE0001','PE0002','PTG0001'); 

INSERT INTO PC_PROCESS
VALUES (TO_CHAR('PRR' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PCR0013','ADMIN0001','PRE0001','PE0002','PTG0001'); 

INSERT INTO P2_PROCESS
VALUES (TO_CHAR('P2P' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'P2R0001','PRE0001','PE0002','ADMIN0001','PTG0001'); 


select *
from p2_report;

SELECT *
FROM P2_process;

SELECT *
FROM PC_PROCESS;

SELECT *
FROM P2_REPORT;

SELECT *
FROM P2_PROCESS;

------------------------------------------------------------- 개설 신청 신고 처리 
SELECT *
FROM APP_OPENING;

SELECT *
FROM AO_COMMENT;

SELECT *
FROM AO_REPLY2;

INSERT INTO AO2_REPORT
VALUES (TO_CHAR('A2R' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),'이거 언제 끝나냐;;;',SYSDATE,'RR0002','MEM0004','A20004');

INSERT INTO AO2_REPORT
VALUES (TO_CHAR('A2R' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),'이거 언제 끝나냐;;;',SYSDATE,'RR0002','MEM0011','A20001');

INSERT INTO AO2_REPORT
VALUES (TO_CHAR('A2R' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),'이거 언제 끝나냐;;;',SYSDATE,'RR0002','MEM0013','A20015');

INSERT INTO AO2_REPORT
VALUES (TO_CHAR('A2R' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),'이거 언제 끝나냐;;;',SYSDATE,'RR0002','MEM0007','A20017');

INSERT INTO AO2_REPORT
VALUES (TO_CHAR('A2R' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),'이거 언제 끝나냐;;;',SYSDATE,'RR0002','MEM0009','A20004');

SELECT *
FROM AO2_REPORT;

COMMIT;

SELECT MEM_CODE, NICKNAME, KDATE, CODE,
  CASE 
    WHEN CODE LIKE 'AOR%' THEN 'AO'
    WHEN CODE LIKE 'ACR%' THEN 'AOC'
    WHEN CODE LIKE 'A2R%' THEN 'A2'
    ELSE ''
  END AS TABLE_CODE
FROM PRO_GET_REPORT_VIEW
WHERE PENALTY = '-1'
ORDER BY MEM_CODE;


INSERT INTO AO_PROCESS
VALUES (TO_CHAR('AOP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE, 'AOR0001','ADMIN0001','PE0002','PRE0002','PTG0001');

INSERT INTO AOC_PROCESS
VALUES (TO_CHAR('ACP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'ADMIN0001','PRE0002', 'ACR0027','PE0002','PTG0001');

INSERT INTO AO2_PROCESS
VALUES (TO_CHAR('A2P' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'ADMIN0001','PRE0002','A2R0035','PE0002','PTG0001');



SELECT *
FROM AO2_PROCESS;

SELECT *
FROM PENALTY;
------------------------------------------------------------------------------------------------------------------ 처리한 신고 처리
-- 개설 게시판 신고
CREATE OR REPLACE VIEW PRO_GET_PROCESS_VIEW
AS
SELECT M.MEM_CODE, M.ID,M.NICKNAME,AO.AOR_CODE AS CODE, RR.REASON,AO.CONTENT, AO.KDATE, NVL(AOR.AOP_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM AO_REPORT AO 
    LEFT JOIN  AO_PROCESS AOR ON AOR.AOR_CODE = AO.AOR_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE= AO.RR_CODE
    JOIN MEMBER M ON M.MEM_CODE = AO.MEM_CODE
    JOIN PENALTY PE ON AOR.PE_CODE = PE.PE_CODE
UNION ALL
(
-- 개설 신청 댓글 신고 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, AOC.ACR_CODE, RR.REASON, AOC.CONTENT, AOC.KDATE, NVL(AOR.ACP_CODE,-1) AS PENALTY, PE.NAME
FROM AOC_REPORT AOC
     LEFT JOIN AOC_PROCESS AOR ON aor.acr_code = aoc.acr_code
     JOIN MEMBER M ON M.MEM_CODE = AOC.MEM_CODE
     JOIN REPORT_REASON RR ON RR.RR_CODE = AOC.RR_CODE
     JOIN PENALTY PE ON AOR.PE_CODE = PE.PE_CODE

)
UNION ALL
(
-- 개설 신청 대댓글 신고 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, AO2.A2R_CODE, RR.REASON, AO2.CONTENT, AO2.KDATE, NVL(AO2P.A2P_CODE,-1) AS PENALTY, PE.NAME
FROM AO2_REPORT AO2
    LEFT JOIN AO2_PROCESS AO2P ON AO2P.A2R_CODE = AO2.A2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = AO2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = AO2.RR_CODE
    JOIN PENALTY PE ON AO2P.PE_CODE = PE.PE_CODE

);

SELECT MEM_CODE,ID,NICKNAME,CODE, REASON, CONTENT, TO_CHAR(KDATE,'YYYY-MM-DD') AS KDATE, PENALTY, PE_NAME
FROM PRO_GET_PROCESS_VIEW
ORDER BY KDATE;

--------------------------------------------------------------------------------- 기술 모든 신고 처리 
-- 기술 개시판 신고 
CREATE OR REPLACE VIEW TQ_GET_PROCESS_VIEW
AS
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQ.TQR_CODE AS CODE, RR.REASON, TQ.CONTENT, TQR.KDATE, NVL(TQR.TQP_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM TQ_REPORT TQ
    LEFT JOIN TQ_PROCESS TQR ON TQ.TQR_CODE = TQR.TQR_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQ.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQ.RR_CODE   
    JOIN PENALTY PE ON TQR.PE_CODE = PE.PE_CODE
UNION ALL
(
-- 기술 게시판 댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQC.QCR_CODE, RR.REASON, TQC.CONTENT, TQCP.KDATE, NVL(TQCP.QCR_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM TQC_REPORT TQC
    LEFT JOIN TQC_PROCESS TQCP ON TQCP.QCR_CODE = TQC.QCR_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQC.RR_CODE
    JOIN PENALTY PE ON TQCP.PE_CODE = PE.PE_CODE

)
UNION ALL
(
-- 기술 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, TQ2.Q2R_CODE, RR.REASON, TQ2.CONTENT, TQ2P.KDATE, NVL(TQ2P.T2P_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM TQ2_REPORT TQ2
    LEFT JOIN TQ2_PROCESS TQ2P ON TQ2P.Q2R_CODE = TQ2.Q2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = TQ2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = TQ2.RR_CODE
    JOIN PENALTY PE ON TQ2P.PE_CODE = PE.PE_CODE

);

-- 기술 모든 신고 처리 
SELECT MEM_CODE,ID,NICKNAME,CODE, REASON, CONTENT, TO_CHAR(KDATE,'YYYY-MM-DD') AS KDATE, PENALTY, PE_NAME
FROM TQ_GET_PROCESS_VIEW
ORDER BY KDATE;


-- 커리어 모든 신고 처리 
CREATE OR REPLACE VIEW CQ_GET_PROCESS_VIEW
AS
-- 커리어 게시판
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQ.QR_CODE AS CODE, RR.REASON, CQ.CONTENT, CQP.KDATE, NVL(CQP.QPR_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM CQ_REPORT CQ
    LEFT JOIN CQ_PROCESS CQP ON CQ.QR_CODE = CQP.QR_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQ.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQ.RR_CODE 
    JOIN PENALTY PE ON CQP.PE_CODE = PE.PE_CODE

UNION ALL
(
--커리어 게시판 댓글 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQC.CR_CODE AS CODE, RR.REASON, CQC.CONTENT, CQCP.KDATE, NVL(CQCP.QCP_CODE,-1) AS PENALTY, PE.NAME AS PE_CODE
FROM CQC_REPORT CQC
    LEFT JOIN CQC_PROCESS CQCP ON CQC.CR_CODE = CQCP.CR_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQC.RR_CODE 
    JOIN PENALTY PE ON CQCP.PE_CODE = PE.PE_CODE
)
UNION ALL
(
-- 커리어 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, CQ2.C2_CODE AS CODE, RR.REASON, CQ2.CONTENT, CQ2.KDATE, NVL(CQ2P.Q2P_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM CQ2_REPORT CQ2
    LEFT JOIN CQ2_PROCESS CQ2P ON CQ2.C2_CODE = CQ2P.C2_CODE
    JOIN MEMBER M ON M.MEM_CODE = CQ2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = CQ2.RR_CODE 
    JOIN PENALTY PE ON CQ2P.PE_CODE = PE.PE_CODE

);

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY, PE_NAME
FROM CQ_GET_PROCESS_VIEW
ORDER BY KDATE;

-- 포트폴리오 모든 신고 처리 
CREATE OR REPLACE VIEW PT_GET_PROCESS_VIEW
AS
SELECT M.MEM_CODE, M.ID, M.NICKNAME, P.PR_CODE AS CODE, RR.REASON, P.CONTENT, PP.KDATE, NVL(PP.PP_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM P_REPORT P
    LEFT JOIN P_PROCESS PP ON P.PR_CODE = PP.PR_CODE
    JOIN MEMBER M ON M.MEM_CODE = P.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = P.RR_CODE
    JOIN PENALTY PE ON PP.PE_CODE = PE.PE_CODE
UNION ALL
(
--포트폴리오 게시판 댓글 
SELECT M.MEM_CODE, M.ID, M.NICKNAME, PC.PCR_CODE AS CODE, RR.REASON, PC.CONTENT, PCP.KDATE, NVL(PCP.PRR_CODE,-1) AS PENALTY, PE.NAME AS PE_CODE
FROM PC_REPORT PC
    LEFT JOIN PC_PROCESS PCP ON PC.PCR_CODE = PCP.PCR_CODE
    JOIN MEMBER M ON M.MEM_CODE = PC.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = PC.RR_CODE 
    JOIN PENALTY PE ON PCP.PE_CODE = PE.PE_CODE

)
UNION ALL
(
-- 포트폴리오 게시판 대댓글
SELECT M.MEM_CODE, M.ID, M.NICKNAME, P2.P2R_CODE AS CODE, RR.REASON, P2.CONTENT, P2P.KDATE, NVL(P2P.P2P_CODE,-1) AS PENALTY, PE.NAME AS PE_NAME
FROM P2_REPORT P2
    LEFT JOIN P2_PROCESS P2P ON P2.P2R_CODE = P2P.P2R_CODE
    JOIN MEMBER M ON M.MEM_CODE = P2.MEM_CODE
    JOIN REPORT_REASON RR ON RR.RR_CODE = P2.RR_CODE
    JOIN PENALTY PE ON P2P.PE_CODE = PE.PE_CODE

);

SELECT MEM_CODE, ID, NICKNAME, CODE, REASON, CONTENT, KDATE, PENALTY, PE_NAME, PE_NAME
FROM PT_GET_PROCESS_VIEW
ORDER BY KDATE;

---------------------------------------------------------- 모든 게시판 개수 조회 
SELECT *
FROM MEMBER
ORDER BY MEM_CODE;

SELECT MBTI_CODE, MBTI
FROM MBTI;

SELECT M.MBTI_CODE, MB.MBTI
FROM MEMBER M JOIN MBTI MB ON M.MBTI_CODE = MB.MBTI_CODE;

UPDATE MEMBER M
SET ID='123123', PW='456123', NICKNAME='현욱짱',MBTI_CODE = (SELECT MBTI_CODE FROM MBTI MB WHERE MBTI='ESFJ')
WHERE MEM_CODE='MEM0001';

delete 
from member
where mem_code='MEM0001';

SELECT *
FROM CLOSE_MEMBER;

delete 
from close_member
where cm_code = 'CM0056';

commit;


-- 탈퇴 안한 사람 조회
SELECT A.MEM_CODE, A.ID, A.PW, A.NICKNAME, A.POST, A.COMMENTS, TO_CHAR(A.KDATE, 'YYYY-MM-DD') AS KDATE, A.MBTI
FROM ALL_MEMBER_VIEW A
        LEFT JOIN CLOSE_MEMBER CR ON CR.MEM_CODE = A.MEM_CODE
WHERE CR.CM_CODE IS NULL
ORDER BY MEM_CODE;


INSERT INTO CLOSE_MEMBER VALUES(TO_CHAR('CM' || LPAD(PP_SEQ.NEXTVAL, 4, '0')),TO_DATE(TO_CHAR(SYSDATE,'YYYY-MM-DD'),'YYYY-MM-DD'), 'MEM0001');

