select user
from dual;
/*
포트폴리오 태그 목록	        PT_LIST             ㅇ
포트폴리오게시판 댓글	        P_COMMENT           ㅇ
프로젝트 (개설확정)	        C_PROJECT           ㅇ
프로젝트 주제 태그 목록	    PTAG_LIST           ㅇ
프로젝트 추가 모집 개설	    ADDITIONAL_OPEN     ㅇ
프로젝트 탈퇴 사유	        W_REASON            ㅇ
프로젝트 탈퇴 팀원 목록	    W_MEMBERLIST        ㅇ
프로젝트 해체	            D_PROJECT           ㅇ
프로젝트 해체 사유	        D_REASON            ㅇ
프로젝트 해체 투표	        D_VOTE              ㅇ
프로필 사진	            PROFILE             ㅇ
항의 게시판 답글	            PROTEST_REPLY       ㅇ
회원 스킬 태그	            SKIL_TAG            ㅇ
회원 정보	                MEM_INFO            ㅇ
회의록	                MINUTES             ㅇ
회의록 댓글	            MI_COMMENT
*/

--100 포토폴리오 태그 
CREATE TABLE P_TAG
( PT_CODE VARCHAR2(10)
, P_CODE VARCHAR2(10)
, PTL_CODE VARCHAR2(10)
, CONSTRAINT PT_PK PRIMARY KEY (PT_CODE)
);
--==>> Table P_TAG이(가) 생성되었습니다.


CREATE SEQUENCE PT_SEQ
START WITH 1
NOCACHE;
--==>> Sequence PT_SEQ이(가) 생성되었습니다.


--101 포폴리오 태그 목록
CREATE TABLE PT_LIST
( PTL_CODE  VARCHAR2(10)
, NAME      VARCHAR2(100)
, CONSTRAINT PTL_PK PRIMARY KEY(PTL_CODE)
);
--==>> Table PT_LIST이(가) 생성되었습니다.

CREATE SEQUENCE PTL_SEQ
START WITH 1
NOCACHE;
--==> Sequence PTL_SEQ이(가) 생성되었습니다.



--102 포트폴리오게시판 댓글 --- 수정하자 
CREATE TABLE P_COMMENT
( PC_CODE    VARCHAR2(10)
, KDATE     DATE DEFAULT SYSDATE
, CONTENT   VARCHAR2(4000)
, P_CODE    VARCHAR2(10)
, MEM_CODE VARCHAR2(10)
, CONSTRAINT PC_PK PRIMARY KEY(PC_CODE)
);
--==> Table P_COMMENT이(가) 생성되었습니다.

CREATE SEQUENCE PC_SEQ
START WITH 1
NOCACHE;
--==>Sequence PC_SEQ이(가) 생성되었습니다.

-- 포트폴리오 게시판에 있는 P_CODE를 참조
ALTER TABLE P_COMMENT
        ADD CONSTRAINT P_P_CODE_FK FOREIGN KEY(P_CODE)
                        REFERENCES PORTFOLIO(P_CODE);
--==>> Table P_COMMENT이(가) 변경되었습니다.

ALTER TABLE P_COMMENT
        ADD CONSTRAINT P_MEM_CODE_FK FOREIGN KEY(MEM_CODE)
                        REFERENCES MEMBER(MEM_CODE);
--==>> Table P_COMMENT이(가) 변경되었습니다.

--103 프로젝트 (개설확정)
CREATE TABLE C_PROJECT
( CP_CODE   VARCHAR2(10)
, KDATE     DATE DEFAULT SYSDATE
, AP_CODE VARCHAR2(10)
, CONSTRAINT CP_PK PRIMARY KEY(CP_CODE)
);
--==>> Table C_PROJECT이(가) 생성되었습니다.

CREATE SEQUENCE CP_SEQ
START WITH 1
NOCACHE;
--==>> Sequence CP_SEQ이(가) 생성되었습니다.

-- 개설 신청에 있는 AP_CODE를 참조 생성(x)
ALTER TABLE C_PROJECT
        ADD CONSTRAINT C_AP_CODE FOREIGN KEY (AP_CODE)
                        REFERENCES APP_OPENING(AP_CODE);
--==>> Table C_PROJECT이(가) 변경되었습니다.


--104 프로젝트 주제 태그 목록
CREATE TABLE PTAG_LIST
( PL_CODE VARCHAR2(10)
, NAME VARCHAR2(100)
, CONSTRAINT PL_PK PRIMARY KEY(PL_CODE)
);
--==>> Table PTAG_LIST이(가) 생성되었습니다.

CREATE SEQUENCE PL_SEQ
START WITH 1
NOCACHE;
--==>> Sequence PL_SEQ이(가) 생성되었습니다.


--105 프로젝트 추가 모집 개설
CREATE TABLE ADDITIONAL_OPEN
( AO_CODE VARCHAR2(10)
, TITLE VARCHAR2(100)
, SUMMARY VARCHAR2(4000)
, CONTENT VARCHAR2(4000)
, KDATE DATE DEFAULT SYSDATE 
, VIEWS NUMBER
, AP_CODE   VARCHAR2(10)
, CONSTRAINT ADDITIONAL_PK PRIMARY KEY(AO_CODE)
);
--==>>Table ADDITIONAL_OPEN이(가) 생성되었습니다.


CREATE SEQUENCE AD_SEQ
START WITH 1
NOCACHE;
--==>> Sequence AD_SEQ이(가) 생성되었습니다.

-- 개설 신청에 있는 AP_CODE를 참조
ALTER TABLE ADDITIONAL_OPEN
        ADD CONSTRAINT ADD_AP_CODE FOREIGN KEY (AP_CODE)
                        REFERENCES APP_OPENING(AP_CODE);
--==>> Table ADDITIONAL_OPEN이(가) 변경되었습니다.

--106 프로젝트 탈퇴 사유	        
CREATE TABLE W_REASON 
( WR_CODE   VARCHAR2(10)
, REASON    VARCHAR2(100)
, PE_CODE   VARCHAR2(10)
, CONSTRAINT WR_PK PRIMARY KEY(WR_CODE)
);
--==>> Table W_REASON이(가) 생성되었습니다.

CREATE SEQUENCE WR_SEQ
START WITH 1
NOCACHE;
--==>> Sequence WR_SEQ이(가) 생성되었습니다.

-- 패널티 테이블의 PE_CODE를 참조함 
ALTER TABLE W_REASON
            ADD CONSTRAINT WR_PE_CODE_FK FOREIGN KEY (PE_CODE)
                                    REFERENCES PENALTY(PE_CODE);
--==>> Table W_REASON이(가) 변경되었습니다.

--107 프로젝트 탈퇴 팀원 목록	
CREATE TABLE W_MEMBERLIST
( WM_CODE   VARCHAR2(10)
, KDATE     DATE DEFAULT SYSDATE
, MA_CODEA  VARCHAR2(10)
, MA_CODEP  VARCHAR2(10)
, WR_CODE   VARCHAR2(10)
, CONSTRAINT WM_PK PRIMARY KEY(WM_CODE)
);
--==>> Table W_MEMBERLIST이(가) 생성되었습니다.


CREATE SEQUENCE WM_SEQ
START WITH 1
NOCACHE;
--==>> Sequence WM_SEQ이(가) 생성되었습니다.

-- 멤버 지원에 있는 MA_CODE를 참조해 방출한 사람을 FK로 구성
ALTER TABLE W_MEMBERLIST
    ADD CONSTRAINT WM_MA_CODEA_FK FOREIGN KEY (MA_CODEA)
                                REFERENCES MEMBER_APPLY(MA_CODE);
--==>> Table W_MEMBERLIST이(가) 변경되었습니다.

                                
-- 멤버 지원에 있는 MA_CODE를 참조해 방출한 사람을 FK로 구성
ALTER TABLE W_MEMBERLIST    
    ADD CONSTRAINT WM_MA_CODEP_FK FOREIGN KEY (MA_CODEP)
                                REFERENCES MEMBER_APPLY(MA_CODE);
--==>> Table W_MEMBERLIST이(가) 변경되었습니다.


--108 프로젝트 해체	
CREATE TABLE D_PROJECT
( DP_CODE   VARCHAR2(10)
, KDATE     DATE DEFAULT SYSDATE 
, CP_CODE   VARCHAR2(10)
, DR_CODE   VARCHAR2(10)
, CONSTRAINT DP_PK PRIMARY KEY (DP_CODE)
);
--==>> Table D_PROJECT이(가) 생성되었습니다.

CREATE SEQUENCE DP_SEQ
START WITH 1
NOCACHE;
--==>> Sequence DP_SEQ이(가) 생성되었습니다.

-- 프로젝트 개설 확정 테이블의 CP_CODE를 참조
ALTER TABLE D_PROJECT 
        ADD CONSTRAINT DP_CP_CODE_FK FOREIGN KEY (CP_CODE)
                        REFERENCES C_PROJECT(CP_CODE);
--==>> Table D_PROJECT이(가) 변경되었습니다.


-- 프로젝트 해체사유 테이블의 DR_CODE를 참조     
ALTER TABLE D_PROJECT 
        ADD CONSTRAINT DP_DR_CODE_FK FOREIGN KEY (DR_CODE)
                        REFERENCES D_REASON(DR_CODE);
--==>> Table D_PROJECT이(가) 변경되었습니다.


--109 프로젝트 해체 사유
CREATE TABLE D_REASON
( DR_CODE   VARCHAR2(10)
, REASON    VARCHAR2(100)
, CONSTRAINT DR_PK PRIMARY KEY(DR_CODE)
);
--==>> Table D_REASON이(가) 생성되었습니다.

CREATE SEQUENCE DR_SEQ
START WITH 1
NOCACHE;
--==>> Sequence DR_SEQ이(가) 생성되었습니다.


--110 프로젝트 해체 투표
CREATE TABLE D_VOTE
( DV_CODE   VARCHAR2(10)
, SDATE     DATE DEFAULT SYSDATE 
, CONTENT   VARCHAR2(500)
, EDATE     DATE
, CP_CODE   VARCHAR2(10)
, CONSTRAINT DV_PK PRIMARY KEY(DV_CODE)
);
--==>> Table D_VOTE이(가) 생성되었습니다.

ALTER TABLE D_VOTE RENAME COLUMN DC_CODE TO DV_CODE;


CREATE SEQUENCE DV_SEQ
START WITH 1
NOCACHE;
--==>> Sequence DV_SEQ이(가) 생성되었습니다.

-- 프로젝트 (개설확정) 테이블의 CP_CODE를 참조
ALTER TABLE D_VOTE
        ADD CONSTRAINT DV_CP_CODE_FK FOREIGN KEY (CP_CODE)
        REFERENCES C_PROJECT(CP_CODE);
--==>> Table D_VOTE이(가) 변경되었습니다.


--111 프로필 사진
CREATE TABLE PROFILE
( PI_CODE   VARCHAR2(10)
, PATH      VARCHAR2(1000)
, MEM_CODE  VARCHAR2(10)
, CONSTRAINT PI_PK PRIMARY KEY(PI_CODE)
);
--==>> Table PROFILE이(가) 생성되었습니다.

CREATE SEQUENCE PI_SEQ
START WITH 1
NOCACHE;
--==>>Sequence PI_SEQ이(가) 생성되었습니다.

-- 일반 회원 테이블의 MEM_CODE를 참조
ALTER TABLE PROFILE
        ADD CONSTRAINT PROF_MEM_CODE_FK FOREIGN KEY (MEM_CODE)
                                    REFERENCES MEMBER(MEM_CODE);
--==>> Table PROFILE이(가) 변경되었습니다.


--112 항의 게시판 답글
CREATE TABLE PROTEST_REPLY
( PROC_CODE VARCHAR2(10)
, KDATE DATE DEFAULT SYSDATE
, CONTENT VARCHAR2(4000)
, PROTEST_CODE  VARCHAR2(10)
, ADMIN_CODE    VARCHAR2(10)
, CONSTRAINT PROC_PK PRIMARY KEY(PROC_CODE)
);
--==>> Table PROTEST_REPLY이(가) 생성되었습니다.

CREATE SEQUENCE PROC_SEQ
START WITH 1
NOCACHE;
--==>> Sequence PROC_SEQ이(가) 생성되었습니다.

-- 고객센터-항의 게시판의 PROTRST_CODE 코드를 참조  
ALTER TABLE PROTEST_REPLY
            ADD CONSTRAINT PROT_PROTEST_CODE_FK FOREIGN KEY(PROTEST_CODE)
            REFERENCES PROTEST(PROTEST_CODE);
--==>> Table PROTEST_REPLY이(가) 변경되었습니다.


ALTER TABLE PROTEST_REPLY
            ADD CONSTRAINT PROT_ADMIN_CODE_FK FOREIGN KEY(ADMIN_CODE)
            REFERENCES ADMIN(ADMIN_CODE);
--==>> Table PROTEST_REPLY이(가) 변경되었습니다.


--113 회원 스킬 태그
CREATE TABLE SKIL_TAG
( KT_CODE   VARCHAR2(10)
, SL_CODE   VARCHAR2(10)
, MEM_CODE  VARCHAR2(10)
, CONSTRAINT KT_PK PRIMARY KEY(KT_CODE)
);
--==>> Table SKIL_TAG이(가) 생성되었습니다.

CREATE SEQUENCE KT_SEQ
START WITH 1
NOCACHE;
--==>> Sequence KT_SEQ이(가) 생성되었습니다.

-- 스킬테그목록 테이블의 SL_CODE를 참
ALTER TABLE SKIL_TAG
            ADD CONSTRAINT SK_SL_CODE_FK FOREIGN KEY(SL_CODE)
            REFERENCES ST_LIST(SL_CODE);
--==>> Table SKIL_TAG이(가) 변경되었습니다.


-- 회원정보 테이블에서 MEM_CODE를 참조
ALTER TABLE SKIL_TAG
            ADD CONSTRAINT SK_MEM_CODE_FK FOREIGN KEY(MEM_CODE)
            REFERENCES  MEMBER(MEM_CODE);
--==>> Table SKIL_TAG이(가) 변경되었습니다.

--114 회원 정보
CREATE TABLE MEM_INFO
( MI_CODE   VARCHAR2(10)
, EMAIL     VARCHAR2(50)
, BDAY      DATE
, ISG_OPEN  NUMBER
, ISB_OPEN  NUMBER
, ISE_OPEN  NUMBER
, MEM_CODE  VARCHAR2(10)
, GENDER_CODE VARCHAR2(10)
, CONSTRAINT MI_PK PRIMARY KEY(MI_CODE)
);
--==>> Table MEM_INFO이(가) 생성되었습니다.

CREATE SEQUENCE MI_SEQ
START WITH 1
NOCACHE;
--==>> Sequence MI_SEQ이(가) 생성되었습니다.

-- 일반 회원 테이블에서 MEM_CODE를 참조
ALTER TABLE MEM_INFO
            ADD CONSTRAINT ME_MEM_CODE_FK FOREIGN KEY(MEM_CODE)
            REFERENCES  MEMBER(MEM_CODE);
--==>> Table MEM_INFO이(가) 변경되었습니다.

ALTER TABLE MEM_INFO
            ADD CONSTRAINT ME_GENDER_CODE_FK FOREIGN KEY(GENDER_CODE)
            REFERENCES  GENDER(GENDER_CODE);
--==>> Table MEM_INFO이(가) 변경되었습니다.

--115 회의록
CREATE TABLE MINUTES
( MN_CODE  VARCHAR2(10)
, KDATE     DATE DEFAULT SYSDATE
, TITLE     VARCHAR2(100)
, CONTENT   VARCHAR2(4000)
, MA_CODE   VARCHAR2(4000)
, CONSTRAINT MN_PK PRIMARY KEY(MN_CODE)
);
--==>> Table MINUTES이(가) 생성되었습니다.

CREATE SEQUENCE MN_SEQ
START WITH 1
NOCACHE;
--==>> Sequence MIN_SEQ이(가) 생성되었습니다.

-- 멤버 지원 테이블에서 MA_CODE를 참
ALTER TABLE MINUTES
            ADD CONSTRAINT MIN_MA_CODE_FK FOREIGN KEY(MA_CODE)
            REFERENCES  MEMBER_APPLY(MA_CODE);
--==>> Table MINUTES이(가) 변경되었습니다.


--116 회의록 댓글
CREATE TABLE MI_COMMENT
( MNC_CODE  VARCHAR2(10)
, COMMENTS   VARCHAR2(4000)
, KDATE     DATE DEFAULT SYSDATE
, MA_CODE   VARCHAR2(10)
, MN_CODE   VARCHAR2(10)
, CONSTRAINT MNC_PK PRIMARY KEY(MNC_CODE)
);
--==>> Table MI_COMMENT이(가) 생성되었습니다.


CREATE SEQUENCE MNC_SEQ
START WITH 1
NOCACHE;
--==>> Sequence MNC_SEQ이(가) 생성되었습니다.

ALTER TABLE MI_COMMENT
            ADD CONSTRAINT MI_MA_CODE_FK FOREIGN KEY(MA_CODE)
            REFERENCES  MEMBER_APPLY(MA_CODE);
--==>> Table MI_COMMENT이(가) 변경되었습니다.


ALTER TABLE MI_COMMENT
            ADD CONSTRAINT MI_MN_CODE_FK FOREIGN KEY(MN_CODE)
            REFERENCES  MINUTES(MN_CODE);
--==>> Table MI_COMMENT이(가) 변경되었습니다.


SELECT *
FROM MEMBER;
-- → TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0'))

------------------ 포트폴리오 게시판
INSERT INTO PORTFOLIO
VALUES (TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0')), '이력서 한번만 봐주세요.', '어쩌구 저쩌구 내용 어쩌구',SYSDATE,2,'MEM0001');

INSERT INTO PORTFOLIO
VALUES (TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0')), '이력서 한번만 봐주라!!.', '삼성 가고 싶어요',SYSDATE,245,'MEM0002');

INSERT INTO PORTFOLIO
VALUES (TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0')), '난 이런 사람이야~!.', '보고 피드백 ㄱㄱ',SYSDATE,17,'MEM0003');

INSERT INTO PORTFOLIO
VALUES (TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0')), '이걸 보면 빠져나갈 수 없어.', '카카오 드가자~',SYSDATE,82,'MEM0004');

INSERT INTO PORTFOLIO
VALUES (TO_CHAR('P' || LPAD(P_SEQ.NEXTVAL, 4, '0')), '너흰 이제 이거 봐줘야 해...', '이 정도면 어디가?',SYSDATE,0,'MEM0005');

SELECT *
FROM PORTFOLIO;

--------- 포트폴리오 게시판 댓글
INSERT INTO P_COMMENT
VALUES (TO_CHAR('PC' || LPAD(PC_SEQ.NEXTVAL, 4, '0')), SYSDATE,'너 이정도면 어디든 못감 ㅋ','P0001','MEM0005');

INSERT INTO P_COMMENT
VALUES (TO_CHAR('PC' || LPAD(PC_SEQ.NEXTVAL, 4, '0')), SYSDATE,'이 정도면 중소 어디든 갈 듯','P0001','MEM0006');

INSERT INTO P_COMMENT
VALUES (TO_CHAR('PC' || LPAD(PC_SEQ.NEXTVAL, 4, '0')), SYSDATE,'이걸로 어딜 갈라고 ㅋ','P0001','MEM0001');

INSERT INTO P_COMMENT
VALUES (TO_CHAR('PC' || LPAD(PC_SEQ.NEXTVAL, 4, '0')), SYSDATE,'되겠냐? ㅋㅋㅋ','P0001','MEM0001');

INSERT INTO P_COMMENT
VALUES (TO_CHAR('PC' || LPAD(PC_SEQ.NEXTVAL, 4, '0')), SYSDATE,'넌 져라','P0001','MEM0002');

SELECT *
FROM P_COMMENT;

------------ 포트폴리오 게시판 대댓글 
INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '쌉소리 할거면 집에 가라 ㅋ','MEM0006', 'PC0003');

INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '어떻게 하면 되는데??','MEM0001', 'PC0003');

INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '내용만 수정하면 될듯?','MEM0002', 'PC0003');

INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '내용만 수정하면 될듯?','MEM0002', 'PC0004');

INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '어머나 이러지 마세요~!','MEM0007', 'PC0005');

INSERT INTO P_REPLY2
VALUES (TO_CHAR('P2' || LPAD(P2_SEQ.NEXTVAL, 4, '0')), SYSDATE, '도배 어떤댕~!~!~!~!~!~!','MEM0009', 'PC0005');

SELECT *
FROM P_REPLY2;


--------- 포트폴리오 태그 목록 
INSERT INTO PT_LIST
VALUES (TO_CHAR('PTL' || LPAD(PTL_SEQ.NEXTVAL, 4, '0')), '자바');

INSERT INTO PT_LIST
VALUES (TO_CHAR('PTL' || LPAD(PTL_SEQ.NEXTVAL, 4, '0')), 'SQL');

INSERT INTO PT_LIST
VALUES (TO_CHAR('PTL' || LPAD(PTL_SEQ.NEXTVAL, 4, '0')), '파이썬');

INSERT INTO PT_LIST
VALUES (TO_CHAR('PTL' || LPAD(PTL_SEQ.NEXTVAL, 4, '0')), '코틀린');

INSERT INTO PT_LIST
VALUES (TO_CHAR('PTL' || LPAD(PTL_SEQ.NEXTVAL, 4, '0')), '자바 스크립트');

SELECT *
FROM PT_LIST;

------------------------------------- 포트폴리오 태그 
INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0005','PTL0001');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0005','PTL0002');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0005','PTL0005');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0002','PTL0003');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0002','PTL0004');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0002','PTL0005');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0003','PTL0001');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0003','PTL0003');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0003','PTL0004');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0004','PTL0001');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0004','PTL0003');

INSERT INTO P_TAG
VALUES (TO_CHAR('PT' || LPAD(PT_SEQ.NEXTVAL, 4, '0')), 'P0004','PTL0004');

SELECT *
FROM P_TAG;

------------------------------------ 포토폴리오 게시판 신고 
INSERT INTO P_REPORT
VALUES (TO_CHAR('PR' || LPAD(PR_SEQ.NEXTVAL, 4, '0')), '나에게 모욕감을 줬습니다;;',SYSDATE, 'P0002','RR0001','MEM0006');

INSERT INTO P_REPORT
VALUES (TO_CHAR('PR' || LPAD(PR_SEQ.NEXTVAL, 4, '0')), '이상한거 만드는것 같은데~~~',SYSDATE, 'P0002','RR0001','MEM0007');

INSERT INTO P_REPORT
VALUES (TO_CHAR('PR' || LPAD(PR_SEQ.NEXTVAL, 4, '0')), '그냥 이상할 것 같아서 신고했어용~!~ 오때?? ^.^',SYSDATE, 'P0003','RR0001','MEM0011');

INSERT INTO P_REPORT
VALUES (TO_CHAR('PR' || LPAD(PR_SEQ.NEXTVAL, 4, '0')), '그냥 이상할 것 같아서 신고했어용~!~ 오때?? 투투 ^.^',SYSDATE, 'P0003','RR0001','MEM0014');

INSERT INTO P_REPORT
VALUES (TO_CHAR('PR' || LPAD(PR_SEQ.NEXTVAL, 4, '0')), '그냥 이상할 것 같아서 신고했어용~!~ 오때?? 투투 ^.^',SYSDATE, 'P0005','RR0001','MEM0013');

SELECT *
FROM P_REPORT;



----------------------------------- 포트폴리오 게시판 댓글 신고 
INSERT INTO PC_REPORT
VALUES (TO_CHAR('PCR' || LPAD(PCR_SEQ.NEXTVAL, 4, '0')), '이런 댓글은 처음 받아봤어;;', SYSDATE,'PC0011', 'RR0001', 'MEM0002');

INSERT INTO PC_REPORT
VALUES (TO_CHAR('PCR' || LPAD(PCR_SEQ.NEXTVAL, 4, '0')), '어떻게 이런 말을 쓸 수가 있지..?', SYSDATE,'PC0012', 'RR0001', 'MEM0003');

INSERT INTO PC_REPORT
VALUES (TO_CHAR('PCR' || LPAD(PCR_SEQ.NEXTVAL, 4, '0')), '얘가 날 건드렸어용... 어쩔건뎅~!~!', SYSDATE,'PC0013', 'RR0001', 'MEM0006');

INSERT INTO PC_REPORT
VALUES (TO_CHAR('PCR' || LPAD(PCR_SEQ.NEXTVAL, 4, '0')), '그래도 열심히 쓴 사람한테 이 말을 하는건 좀...', SYSDATE,'PC0011', 'RR0001', 'MEM0001');

SELECT *
FROM PC_REPORT;



COMMIT;

---------------------------------------- 포트폴리오 게시판 대댓글 신고 
INSERT INTO P2_REPORT 
VALUES (TO_CHAR('P2R' || LPAD(P2R_SEQ.NEXTVAL, 4, '0')), '욕설 했어용!!!!!',SYSDATE, 'RR0001','P20013','MEM0005');

INSERT INTO P2_REPORT 
VALUES (TO_CHAR('P2R' || LPAD(P2R_SEQ.NEXTVAL, 4, '0')), '이런 심한 말을...?',SYSDATE,'RR0001','P20003','MEM0009');

INSERT INTO P2_REPORT 
VALUES (TO_CHAR('P2R' || LPAD(P2R_SEQ.NEXTVAL, 4, '0')), '난 이사람을 본적이 없는데 왜 이렇게 심한말은 하는거죠? 바로  고소 드갈게용...',SYSDATE, 'RR0001','P20005','MEM0008');

INSERT INTO P2_REPORT 
VALUES (TO_CHAR('P2R' || LPAD(P2R_SEQ.NEXTVAL, 4, '0')), '도배 바로 쳐내 쳐내~!',SYSDATE, 'RR0001','PC0006','MEM0008');

SELECT *
FROM P2_REPORT;

UPDATE P2_REPORT
SET P2_CODE = 'P20014'
WHERE P2R_CODE = 'P2R0007';

SELECT *
FROM P_REPLY2;

----------------------------------------- 포트폴리오 게시판 신고 처리 
INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0011','ADMIN0001','PRE0001','PE0002','PTG0001'); 

INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0007','ADMIN0002','PRE0001','PE0001','PTG0001');

INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0008','ADMIN0002','PRE0001','PE0003','PTG0002');

INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0009','ADMIN0003','PRE0001','PE0002','PTG0002');

INSERT INTO P_PROCESS
VALUES (TO_CHAR('PP' || LPAD(PP_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PR0010','ADMIN0001','PRE0001','PE0001','PTG0001'); 

SELECT *
FROM P2_PROCESS;

----------------------------------------- 포트폴리오 게시판 댓글 신고 처리 
INSERT INTO PC_PROCESS
VALUES (TO_CHAR('PRR' || LPAD(PRR_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PCR0001','ADMIN0001', 'PRE0001', 'PE0001','PTG0002');

INSERT INTO PC_PROCESS
VALUES (TO_CHAR('PRR' || LPAD(PRR_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PCR0002','ADMIN0001', 'PRE0001', 'PE0001','PTG0002');

INSERT INTO PC_PROCESS
VALUES (TO_CHAR('PRR' || LPAD(PRR_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PCR0003','ADMIN0003', 'PRE0001', 'PE0001','PTG0001');

INSERT INTO PC_PROCESS
VALUES (TO_CHAR('PRR' || LPAD(PRR_SEQ.NEXTVAL, 4, '0')), SYSDATE,'PCR0004','ADMIN0001','PRE0001', 'PE0001','PTG0002');

SELECT *
FROM PC_PROCESS;

---------------------------------------------- 포트폴리오 게시판 대댓글 신고 처리 

INSERT INTO P2_PROCESS
VALUES (TO_CHAR('P2P' || LPAD(P2P_SEQ.NEXTVAL, 4, '0')),SYSDATE, 'P2R0001', 'PRE0001','PE0001','ADMIN0002','PTG0001');

INSERT INTO P2_PROCESS
VALUES (TO_CHAR('P2P' || LPAD(P2P_SEQ.NEXTVAL, 4, '0')),SYSDATE, 'P2R0002', 'PRE0001','PE0002','ADMIN0003','PTG0001');

INSERT INTO P2_PROCESS
VALUES (TO_CHAR('P2P' || LPAD(P2P_SEQ.NEXTVAL, 4, '0')),SYSDATE, 'P2R0003', 'PRE0001','PE0003','ADMIN0001','PTG0002');

INSERT INTO P2_PROCESS
VALUES (TO_CHAR('P2P' || LPAD(P2P_SEQ.NEXTVAL, 4, '0')),SYSDATE, 'P2R0004', 'PRE0001','PE0001','ADMIN0001','PTG0002');

SELECT *
FROM P2_PROCESS;

--TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0'))
------------------------------------------------ 회의록 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 1회차 회의록', '오전 : 데이터 생성하고, 오후 : SELECT문 작성','MA0001'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0001'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0002');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0002'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0003');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0003'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0004');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '3월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0004');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0005');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0005'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 8회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0006');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 9회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0006'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '4월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0007');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '4월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0007'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0008');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0008'); 

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 1회차 회의록', '오전 : 데이터 생성, 오후 : SELECT문 작성','MA0009');

INSERT INTO MINUTES
VALUES(TO_CHAR('MN' || LPAD(MN_SEQ.NEXTVAL, 4, '0')),SYSDATE, '2월 2회차 회의록', '오전 : SELECT문 작성, 오후 : 프로시저 생성','MA0009'); 

SELECT *
FROM MINUTES;

------------------------------------ 회의록 댓글 
INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '잘하신것 같네요', SYSDATE,'MA0001','MN0002'); 

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '잘하셨어요~!!', SYSDATE,'MA0003','MN0002');

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '이 내용 쪼까 부족한것 같은데용??', SYSDATE,'MA0004','MN0003'); 

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '굿굿굿', SYSDATE,'MA0005','MN0001');

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '굿굿굿', SYSDATE,'MA0006','MN0001');

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '굿굿굿', SYSDATE,'MA0007','MN0001');

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '굿굿굿', SYSDATE,'MA0008','MN0001');

INSERT INTO MI_COMMENT
VALUES (TO_CHAR('MNC' || LPAD(MNC_SEQ.NEXTVAL, 4, '0')), '굿굿굿', SYSDATE,'MA0009','MN0001');

--------------------------------------------------------------------------------- 매너 점수 필터링
INSERT INTO MS_FILTER
VALUES (TO_CHAR('MSF' || LPAD(MSF_SEQ.NEXTVAL, 4, '0')), 36,'AP0001');

INSERT INTO MS_FILTER
VALUES (TO_CHAR('MSF' || LPAD(MSF_SEQ.NEXTVAL, 4, '0')), 0,'AP0002');

INSERT INTO MS_FILTER
VALUES (TO_CHAR('MSF' || LPAD(MSF_SEQ.NEXTVAL, 4, '0')), 37,'AP0003');

INSERT INTO MS_FILTER
VALUES (TO_CHAR('MSF' || LPAD(MSF_SEQ.NEXTVAL, 4, '0')), 34,'AP0004');

SELECT *
FROM MS_FILTER;

-------------------------------------------------------------------------------------- 나이 필터링 
INSERT INTO A_FILTER 
VALUES (TO_CHAR('AF' || LPAD(AF_SEQ.NEXTVAL, 4, '0')), 'AP0001', 'AA0003');

INSERT INTO A_FILTER 
VALUES (TO_CHAR('AF' || LPAD(AF_SEQ.NEXTVAL, 4, '0')), 'AP0002', 'AA0004');

INSERT INTO A_FILTER 
VALUES (TO_CHAR('AF' || LPAD(AF_SEQ.NEXTVAL, 4, '0')), 'AP0003', 'AA0005');

INSERT INTO A_FILTER 
VALUES (TO_CHAR('AF' || LPAD(AF_SEQ.NEXTVAL, 4, '0')), 'AP0004', 'AA0001');

INSERT INTO A_FILTER 
VALUES (TO_CHAR('AF' || LPAD(AF_SEQ.NEXTVAL, 4, '0')), 'AP0005', 'AA0002');

SELECT *
FROM A_FILTER;

------------------------------------------------------------------------ 등급 필터링 
INSERT INTO G_FILTER
VALUES (TO_CHAR('GF' || LPAD(GF_SEQ.NEXTVAL, 4, '0')), 'GRADE0001','MR0002', 'AP0001');

INSERT INTO G_FILTER
VALUES (TO_CHAR('GF' || LPAD(GF_SEQ.NEXTVAL, 4, '0')), 'GRADE0002','MR0002', 'AP0002');

INSERT INTO G_FILTER
VALUES (TO_CHAR('GF' || LPAD(GF_SEQ.NEXTVAL, 4, '0')), 'GRADE0003','MR0003', 'AP0003');

INSERT INTO G_FILTER
VALUES (TO_CHAR('GF' || LPAD(GF_SEQ.NEXTVAL, 4, '0')), 'GRADE0004','MR0003', 'AP0004');

INSERT INTO G_FILTER
VALUES (TO_CHAR('GF' || LPAD(GF_SEQ.NEXTVAL, 4, '0')), 'GRADE0005','MR0002', 'AP0005');

SELECT *
FROM G_FILTER;

------------------------------------------------------------------------------- 성별 필터링 
INSERT INTO S_FILTER
VALUES(TO_CHAR('SF' || LPAD(SF_SEQ.NEXTVAL, 4, '0')), 'GENDER0001', 'AP0001');

INSERT INTO S_FILTER
VALUES(TO_CHAR('SF' || LPAD(SF_SEQ.NEXTVAL, 4, '0')), 'GENDER0001', 'AP0002');

INSERT INTO S_FILTER
VALUES(TO_CHAR('SF' || LPAD(SF_SEQ.NEXTVAL, 4, '0')), 'GENDER0002', 'AP0003');

INSERT INTO S_FILTER
VALUES(TO_CHAR('SF' || LPAD(SF_SEQ.NEXTVAL, 4, '0')), 'GENDER0002', 'AP0004');

INSERT INTO S_FILTER
VALUES(TO_CHAR('SF' || LPAD(SF_SEQ.NEXTVAL, 4, '0')), 'GENDER0001', 'AP0005');

SELECT *
FROM S_FILTER;

------------------------------------------------------------------------- 프로젝트 해체 투표 
INSERT INTO D_VOTE
VALUES (TO_CHAR('DV' || LPAD(DV_SEQ.NEXTVAL, 4, '0')),TO_DATE('2024-02-09','YYYY-MM-DD'), '팀장이 폐급입니다...',TO_DATE('2024-02-14','YYYY-MM-DD'),'CP0001');

SELECT *
FROM D_VOTE;

---------------------------------------------------------------------- 투표 
INSERT INTO AG_LIST
VALUES (TO_CHAR('AL' || LPAD(AL_SEQ.NEXTVAL, 4, '0')),'MA0001', 'DV0001');

INSERT INTO AG_LIST
VALUES (TO_CHAR('AL' || LPAD(AL_SEQ.NEXTVAL, 4, '0')),'MA0002', 'DV0001');

SELECT *
FROM AG_LIST;

------------------------------------------------------------------------ 태스크
INSERT INTO TT_LIST
VALUES (TO_CHAR('TTL' || LPAD(TTL_SEQ.NEXTVAL, 4, '0')), '뷰페이지 만들기');

INSERT INTO TT_LIST
VALUES (TO_CHAR('TTL' || LPAD(TTL_SEQ.NEXTVAL, 4, '0')), '테이블 생성');

INSERT INTO TT_LIST
VALUES (TO_CHAR('TTL' || LPAD(TTL_SEQ.NEXTVAL, 4, '0')), '회의록 작성');

INSERT INTO TT_LIST
VALUES (TO_CHAR('TTL' || LPAD(TTL_SEQ.NEXTVAL, 4, '0')), 'SQL 연결');

SELECT *
FROM TT_LIST;

-------------------------------------------------------------------- 태스크 태그 
INSERT INTO TASK_TAG
VALUES (TO_CHAR('TT' || LPAD(TT_SEQ.NEXTVAL, 4, '0')),'TTL0001','TASK0001');

INSERT INTO TASK_TAG
VALUES (TO_CHAR('TT' || LPAD(TT_SEQ.NEXTVAL, 4, '0')),'TTL0002','TASK0002');

SELECT *
FROM TASK_TAG;

------------------------------------------------------------------------------- 프로젝트 해체 
INSERT INTO D_PROJECT 
VALUES (TO_CHAR('TT' || LPAD(TT_SEQ.NEXTVAL, 4, '0')), SYSDATE,'CP0001', 'DR0001');

SELECT *
FROM D_PROJECT;

------------------------------------------------------------------------------------ 평가 
INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 5, 'ED0001','MA0001','MA0002');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 3, 'ED0002','MA0001','MA0002');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 5, 'ED0001','MA0002','MA0001');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 3, 'ED0002','MA0002','MA0001');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 1, 'ED0001','MA0002','MA0003');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 2, 'ED0002','MA0002','MA0003');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 1, 'ED0001','MA0003','MA0002');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 1, 'ED0002','MA0003','MA0002');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 4, 'ED0001','MA0001','MA0003');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 4, 'ED0002','MA0001','MA0003');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 5, 'ED0001','MA0003','MA0001');

INSERT INTO EVALUATION
VALUES (TO_CHAR('EV' || LPAD(EV_SEQ.NEXTVAL, 4, '0')), SYSDATE, 2, 'ED0002','MA0003','MA0001');

SELECT *
FROM EVALUATION;

----------------------------------------------------------------------------------------- 결산 보고서 
INSERT INTO FINAL_REPORT 
VALUES (TO_CHAR('FR' || LPAD(FR_SEQ.NEXTVAL, 4, '0')),'결과 보고서','내용입니다.',TO_DATE('2024-02-29','YYYY-MM-DD'), 'CP0001');

SELECT *
FROM FINAL_REPORT;

----------------------------------------------------------------------------------------- 팀장 방출
INSERT INTO RELEASE
VALUES (TO_CHAR('RE' || LPAD(RE_SEQ.NEXTVAL, 4, '0')), SYSDATE, 'TASK0001','CP0001');

SELECT *
FROM RELEASE;

------------------------------------------------------------------------------------- 팀장 위임 
INSERT INTO D_LEADER
VALUES (TO_CHAR('DL' || LPAD(DL_SEQ.NEXTVAL, 4, '0')), SYSDATE, 'MA0003','RE0001');

SELECT *
FROM D_LEADER;

----------------------------------------------------------------------------------- ERD
INSERT INTO ERD
VALUES (TO_CHAR('ERD' || LPAD(DL_SEQ.NEXTVAL, 4, '0')), 'https://www.erdcloud.com/d/9A5ig9f7TQCyxe4Pj', 'FR0008');

INSERT INTO ERD
VALUES (TO_CHAR('ERD' || LPAD(DL_SEQ.NEXTVAL, 4, '0')), 'https://www.naver.com', 'FR0008');

INSERT INTO ERD
VALUES (TO_CHAR('ERD' || LPAD(DL_SEQ.NEXTVAL, 4, '0')), 'https://maplestory.nexon.com/Home/Main', 'FR0008');

SELECT *
FROM ERD;

--------------------------------------------------------------- 순서도 
INSERT INTO FLOWCHART
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'https://fonts.google.com/icons?selected=Material+Symbols+Outlined:settings:FILL@0;wght@400;GRAD@0;opsz@24', 'FR0008');

INSERT INTO FLOWCHART
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'https://fonts.google.com/icons?selected=Material+Symbols+Outlined:settings:FILL@0;wght@400;GRAD@0;opsz@21', 'FR0008');

INSERT INTO FLOWCHART
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'https://fonts.google.com/icons?selected=Material+Symbols+Outlined:settings:FILL@0;wght@400;GRAD@0;opsz@17', 'FR0008');

SELECT *
FROM FLOWCHART;

----------------------------------------------------------------------------------
INSERT INTO FR_FILE
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'C:\Downloads','FR0008');

INSERT INTO FR_FILE
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'C:\Downloads','FR0008');

INSERT INTO FR_FILE
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'C:\Downloads','FR0008');

INSERT INTO FR_FILE
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'C:\Downloads','FR0008');

INSERT INTO FR_FILE
VALUES (TO_CHAR('FC' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), 'C:\Downloads','FR0008');

SELECT *
FROM FR_FILE;

-----------------------------------------------------------------------------------
INSERT INTO TEAM_FEEDBACK
VALUES (TO_CHAR('TF' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), '증말 주옥같은 시간이였습니다. 다신 안해',SYSDATE, 'MA0001', 'FR0008');

INSERT INTO TEAM_FEEDBACK
VALUES (TO_CHAR('TF' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), '정말 좋은 시간이였고 HTML과 VIEW 다신 안해',SYSDATE, 'MA0002', 'FR0008');

INSERT INTO TEAM_FEEDBACK
VALUES (TO_CHAR('TF' || LPAD(FC_SEQ.NEXTVAL, 4, '0')), '정말 가 족같은 분위기 속에서 프로젝트 하니가 참 즐거운 시간이였음 ㅋ',SYSDATE, 'MA0003', 'FR0008');

SELECT *
FROM TEAM_FEEDBACK;

---------------------------------------------------------------------------- 체크리스트 
INSERT INTO CHECKLIST
VALUES (TO_CHAR('CK' || LPAD(CK_SEQ.NEXTVAL, 4, '0')), '제일 먼저 뷰 페이지 만들기', SYSDATE, 'ST0001', 


SELECT *
FROM CHECKLIST;

SELECT *
FROM STEP;

SELECT *
FROM EV_DEVISION;

SELECT *
FROM TASK;

-- 탈퇴 사유 
SELECT *
FROM D_REASON;

-- 개설 확정
SELECT *
FROM C_PROJECT;

SELECT *
FROM A_RESULT;

SELECT *
FROM APP_OPENING;

SELECT *
FROM MEMBER_APPLY;

SELECT *
FROM ROLE_COMP;

SELECT *
FROM MILESTONE;

------------------------------------------------------------------- 쿼리문
SELECT *
FROM APP_OPENING;

SELECT *
FROM MEMBER;

SELECT *
FROM TECH_QNA;

SELECT *
FROM C_QnA;

SELECT *
FROM PORTFOLIO;


